//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBaseManager
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class Dostawy
    {
        public int id_dostawy { get; set; }
        public Nullable<int> id_produktu { get; set; }
        public Nullable<decimal> ilosc { get; set; }
        public System.DateTime data_dostawy { get; set; }
        public Nullable<decimal> cena_zakupu { get; set; }
        public Nullable<decimal> cena_netto { get; set; }
        public Nullable<decimal> cena_brutto { get; set; }
    
        public virtual Produkty Produkty { get; set; }
    }
}
